# Ghost 3.35

# Pull base image.
FROM ghost:3.35

# Set environment variables.
ENV NODE_ENV development

# Define working directory.
WORKDIR /var/lib/ghost

# Define default command.
# CMD ["ghost", "start"]

# Expose ports.
EXPOSE 2368