# Ghost 3.35

# Pull base image.
FROM ghost:3.35

# Set environment variables.
ENV NODE_ENV development

USER node:node

# Define working directory.
WORKDIR /var/lib/ghost/content

# Expose ports.
EXPOSE 2368